---
title: "ʚ♡ɞ Final Project - Starbucks ʚ♡ɞ"
---

## So... what's this about?

As part of the final project of NM2207, we are to construct a data story from a data set of our own choosing. With that in mind, I've chosen to base my data story and project on a data set I've found about Starbucks branches in California!

I'm interested to poke around and explore any observable links and correlations between the common-ness of Starbucks branches and the frequency of certain profiles of the residents, and see what that says about certain stereotypes and branding associated with Starbucks. This is because I am a fan of sweet, iced drinks, and I used to go to Starbucks (the Singapore branches) often to get my fix of coffee or matcha frappuccinos.

Here is an embedded Shiny app for you to explore the plots of the Starbucks dataset variables! Join me and try to spot any trends!!

<iframe height="1200" width="200%" frameborder="no" src="https://nusyjying.shinyapps.io/StarbiesPlotApp/"> </iframe>

## Personal thoughts

Through this project, my main questions were that "Does Starbucks everyday association and correlation to (the white) race and socioeconomic status (SES) offer any insightful reflections on consumer culture, social stratification, and branding?" and "Otherwise, is it all just a matter of stereotyping and coincidence?". 

From my own exploration of this plot visualisation app, I personally observe that there doesn't seem to be a strong correlation between the proportion of Starbucks distribution and most of my variables of concern. The scatterplots do seem quite sparsely separated in the generated graphs, and 

I’m personally looking at Percentage of white population, Median household income, Median age, Number of Starbucks, Starbucks per million inhabitants, and Starbucks per 10 sq mile. In particular, I want to pay special attention to **Starbucks per million inhabitants** as a way for me to relate the differing populations of the different geographical locations to give me the most apt proportion of Starbucks distribution.

Ultimately, the weak correlation tells me that the association between the frequency of Starbucks branches and outlets in a particular geographical location and factors such as population whiteness, age, and SES is weak. However, the observable positive correlation in the plots between "percentage of white population and Starbucks per million inhabitants" and "median age and Starbucks per million inhabitants" is apparent, which at least suggests that the stereotype that Starbucks leans towards a customer profile and target of satisfaction that may be prominently White. 

Interestingly, the plotted graph between "median household income" and "Starbucks per million inhabitants" shows no correlation unlike what I expected given the common perception that Starbucks is considered an 'everyday luxury' or 'treat'. (Insert more findings and thoughts here as this is still in the works)
